### ISSUE TITLE
Petpet error

### ISSUE THREAD

**Issue by ikeman2003** [Wolfkid200444/hot-plugins#6]
Oops! Something went wrong while running this command:
java.lang.AssertionError: Assertion failed

Please search for this error on the Aliucord server to see if it's a known issue. If it isn't, report it to the plugin authors (Wolfie, Alyxia).

Debug:
Command: petpet
Plugin: PetPet v1.1.5
Discord v124012
Android 11 (SDK 30)
Aliucord eb3b861

Arguments:
name=506186003816513538

Getting this error when attempting to run /petpet

**Comment by Wolfkid200444** [comment]
this got fix

**Comment by scryptic1** [comment]
> this got fix

I also have this problem
